### ISSUE TITLE
Argo doesn't reconcile into guestbook-gitops NS

### ISSUE THREAD

**Issue by eriknelson** [konveyor/crane-runner#12]
**What version of crane are you running, and what are your clutsters+platform**

```
crane:
  Version: v0.0.3
crane-lib:
  Version: v0.0.5
```

**What date were you attending the hackathon?**

N/A

**What scenario were you running when you encountered the issue?**

003 Gitops

**What did you expect to happen?**

When I created the argocd application, it originally wouldn't reconcile because
my manifests upon upload were stored in a dir called "base" rather than "app",
which is what the Application in the readme is configured to look for. Once
I `k edit` the application and changed the path to "base", then it found my
manifests. I would have expected argo to recognize the kustomize.yml file that
was in my repo that I think was supposed to overlay the namespace to be set to
`guestbook-gitops`, so that I would have ended up with the guestbook in that
namespace.

**What actually happened?**

I still had a `guestbook` ns on my dest cluster that had the mirrored stateless
app from example 001. I think argo was looking at this app and thought that it
already had the resources there. But it shouldn't have been looking there at all,
since it should have used the kustomize overlay.

**Please include any relevant logs or errors**

Saw this on the status of the application.

```
syncResult:
resources:
- group: ""
  hookPhase: Running
  kind: Secret
  message: secret/default-token-h2l5d created
  name: default-token-h2l5d
  namespace: guestbook
  status: Synced
  syncPhase: Sync
  version: v1
```

**Comment by eriknelson** [comment]
Noticing this:

```
  sync:
    comparedTo:
      destination:
        namespace: guestbook-gitops
        server: https://kubernetes.default.svc
      source:
        path: base
        repoURL: https://github.com/eriknelson/crane-guestbook-gitops.git
        targetRevision: master
    revision: 1222bf5370128a08fa3d129d08280afb3ba7d342
```

So it seems to think it should go into guestbook-gitops?
